#!/bin/bash -E
source $(cd $(dirname $0) && pwd)/common.sh

doclone() {(
  PARENTDIR=$1
  SUBDIR=$2
  REPO=$3
  cd ${SRCROOT}
  mkdir -p $PARENTDIR
  if [ ! -d "$PARENTDIR/$SUBDIR" ]; then
    cd $PARENTDIR && git clone $REPO $SUBDIR && cd $SUBDIR && git config branch.master.rebase true
  fi
)}

dopatch() {(
  PARENTDIR=$1
  SUBDIR=$2
  REPO=$3
  # Check to see if any exist
  if ls ${BASEDIR}/patches/${SUBDIR}*.patch >/dev/null 2>&1; then
    echo "Applying patches to ${SUBDIR}"
    cd ${SRCROOT}/${PARENTDIR}/${SUBDIR}
    for patchfile in ${BASEDIR}/patches/${SUBDIR}*.patch; do
      git am ${patchfile} >/dev/null 2>&1 && echo "Applied ${patchfile}" || (git am --abort; echo "${patchfile} already applied!")
    done
  else
    echo "No patches for ${SUBDIR}"
  fi

)}
(
  mkdir -p ${SRCROOT}
  ineachrepo doclone
  ineachrepo dopatch

  CLANG_TOOLS_CMAKE=${SRCROOT}/llvm/tools/clang/tools/CMakeLists.txt
  if grep "include-what-you-use" $CLANG_TOOLS_CMAKE; then
    echo "Clang tools CMake already has IWYU added."
  else
    echo "Adding entry for IWYU to Clang tools CMake."
    echo "add_llvm_external_project(include-what-you-use include-what-you-use)" >> $CLANG_TOOLS_CMAKE
    (
      cd $(dirname ${CLANG_TOOLS_CMAKE}) && git add ${CLANG_TOOLS_CMAKE} && git commit -m "Add IWYU to build system"
    )
  fi
)
