#!/bin/bash -E
source $(cd $(dirname $0) && pwd)/common.sh

(
  if [ -x "${PREFIX}/bin/clang" -a -x "${PREFIX}/bin/clang++" ]; then
    echo "Using previous build of Clang for CC/CXX"
    export CC=${PREFIX}/bin/clang
    export CXX=${PREFIX}/bin/clang++
  else
    echo "Bootstrapping - using system CC/CXX"
  fi

  mkdir -p $BUILDDIR && cd $BUILDDIR

  rm -rf CMakeCache.txt CMakeFiles
  cmake $SRCDIR \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    "-DLLVM_TARGETS_TO_BUILD=${TARGETS}"
)
