#!/bin/bash -E
source $(cd $(dirname $0) && pwd)/common.sh

(
  if [ -x "${INSTALLDIR}/bin/clang" -a -x "${INSTALLDIR}/bin/clang++" ]; then
    echo "Using previous build of Clang for CC/CXX"
    export CC=${INSTALLDIR}/bin/clang
    export CXX=${INSTALLDIR}/bin/clang++  
  else
    echo "Bootstrapping - using system CC/CXX"
  fi

	mkdir -p $BUILDDIR && cd $BUILDDIR

	rm -rf CMakeCache.txt CMakeFiles
  cmake $SRCDIR \
    -DCMAKE_INSTALL_PREFIX=$INSTALLDIR \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_TARGETS_TO_BUILD=X86
)
